import React, { useEffect, useState } from 'react';
import { WebsiteService } from '../services/websiteService';
import { BrokerProfile, WebsitePage, Investor } from '../types';
import { InvestorService } from '../services/investorService';
import { useToast } from '../contexts/ToastContext';
import { Icons } from '../components/Icons';
import { Logo } from '../components/Logo';

export const PublicWebsite = () => {
    const [loading, setLoading] = useState(true);
    const [profile, setProfile] = useState<BrokerProfile | null>(null);
    const [pages, setPages] = useState<WebsitePage[]>([]);
    const [activePage, setActivePage] = useState<WebsitePage | null>(null);
    const [notFound, setNotFound] = useState(false);

    // Contact Form State
    const [formState, setFormState] = useState({ name: '', email: '', phone: '', message: '' });
    const [sending, setSending] = useState(false);
    const [sent, setSent] = useState(false);
    const { showToast } = useToast();

    useEffect(() => {
        const loadSite = async () => {
            const pathParts = window.location.pathname.split('/').filter(Boolean);
            // Expected format: /site/[subdomain]/[optional: page-slug]
            // pathParts[0] = 'site'
            // pathParts[1] = subdomain
            // pathParts[2] = page slug (optional, defaults to 'home')

            const subdomain = pathParts[1];
            const slug = pathParts[2] || 'home';

            if (!subdomain) {
                setNotFound(true);
                setLoading(false);
                return;
            }

            const data = await WebsiteService.getPublicSite(subdomain);

            if (!data) {
                setNotFound(true);
            } else {
                setProfile(data.profile);
                setPages(data.pages);

                // Find active page
                const page = data.pages.find(p => p.slug === slug) || data.pages.find(p => p.slug === 'home');
                setActivePage(page || null);
            }
            setLoading(false);
        };

        loadSite();
    }, []);

    const handleContactSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!profile?.id) return;

        setSending(true);
        try {
            // Create investor linked to this broker
            const newInvestor: any = { // ID is generated by DB
                name: formState.name,
                email: formState.email,
                phone: formState.phone,
                // We could add a note or source field if supported
            };

            // We need a way to link to the specific broker. 
            // InvestorService.createInvestor uses the CURRENT user's session.
            // Since this is public, we need a public endpoint or RPC.
            // For now, let's assume we have a public RPC or similar.
            // WAIT - InvestorService uses supabase.auth.user(). This won't work for public visitors.
            // We need a specific public RPC: `create_public_investor(profile_id, name, email, phone)`

            // For MVP, we'll try to use a Supabase Function or just direct insert if RLS allows public insert with profile_id
            // RLS usually blocks public insert. 
            // I'll add a note to create a public RPC for this.
            // For now, I'll simulate success or handle via specific endpoint if I can.

            // Actually, I'll update InvestorService to support public submission if I can, 
            // but realistically I need to add a new RPC for this.
            // Let's assume there's a hypothetical `submitPublicLead` method in WebsiteService.

            await WebsiteService.submitLead(profile.id, newInvestor);

            setSent(true);
            showToast('Message sent! We will be in touch shortly.', 'success');
        } catch (e) {
            console.error('Failed to submit form', e);
            showToast('Failed to send message', 'error');
        } finally {
            setSending(false);
        }
    };

    if (loading) {
        return <div className="min-h-screen flex items-center justify-center bg-gray-50"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div></div>;
    }

    if (notFound || !profile) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 text-center px-4">
                <Logo />
                <h1 className="text-2xl font-bold mt-8 text-slate-900">Site Not Found</h1>
                <p className="text-muted mt-2">The website you are looking for does not exist or has been moved.</p>
                <a href="/" className="mt-6 text-primary hover:underline">Go to DealFlow</a>
            </div>
        );
    }

    // Theme Variables
    const theme = profile.websiteSettings?.theme || 'modern';
    // We could apply different CSS classes based on theme

    return (
        <div className="min-h-screen flex flex-col bg-white font-sans text-slate-900">
            {/* Navbar */}
            <nav className="sticky top-0 z-50 w-full bg-white/80 backdrop-blur-md border-b border-gray-100">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex justify-between items-center h-16">
                        <div className="flex items-center gap-3">
                            {profile.logoUrl ? (
                                <img src={profile.logoUrl} alt={profile.name} className="h-8 w-auto object-contain" />
                            ) : (
                                <div className="text-xl font-bold tracking-tight">{profile.company || profile.name}</div>
                            )}
                        </div>
                        <div className="hidden md:flex gap-8">
                            {pages.map(page => (
                                <a
                                    key={page.id}
                                    href={`/site/${profile.websiteSubdomain}/${page.slug === 'home' ? '' : page.slug}`}
                                    className={`text-sm font-medium transition-colors ${activePage?.id === page.id ? 'text-primary' : 'text-slate-600 hover:text-slate-900'}`}
                                >
                                    {page.title}
                                </a>
                            ))}
                            <a href="#contact" className="px-4 py-2 bg-slate-900 text-white text-sm font-medium rounded-full hover:bg-slate-800 transition-colors">
                                Contact
                            </a>
                        </div>
                        {/* Mobile Menu Button - Todo */}
                    </div>
                </div>
            </nav>

            {/* Main Content */}
            <main className="flex-grow">
                {activePage ? (
                    <div className="animate-in fade-in duration-500">
                        {/* Render Page Sections */}
                        {activePage.content?.sections?.map((section: any, idx: number) => {
                            if (section.type === 'hero') {
                                return (
                                    <section key={idx} className="relative py-20 lg:py-32 overflow-hidden">
                                        <div className="absolute inset-0 bg-gradient-to-br from-slate-50 to-white -z-10" />
                                        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
                                            <h1 className="text-4xl sm:text-6xl font-black tracking-tight text-slate-900 mb-6">
                                                {section.heading}
                                            </h1>
                                            <p className="text-lg sm:text-xl text-slate-600 max-w-2xl mx-auto mb-10 leading-relaxed">
                                                {section.subheading}
                                            </p>
                                            {section.ctaText && (
                                                <a href={section.ctaLink || '#contact'} className="inline-flex items-center justify-center px-8 py-4 text-base font-bold text-white bg-primary rounded-full hover:bg-primary/90 transition-all shadow-lg hover:shadow-xl hover:-translate-y-0.5">
                                                    {section.ctaText}
                                                </a>
                                            )}
                                        </div>
                                    </section>
                                );
                            }

                            if (section.type === 'text') {
                                return (
                                    <section key={idx} className="py-16 bg-white">
                                        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
                                            <div className="prose prose-lg text-slate-600">
                                                <div dangerouslySetInnerHTML={{ __html: section.html }} />
                                            </div>
                                        </div>
                                    </section>
                                );
                            }

                            if (section.type === 'features') {
                                return (
                                    <section key={idx} className="py-20 bg-slate-50">
                                        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                                            {section.heading && <h2 className="text-3xl font-bold text-center mb-12">{section.heading}</h2>}
                                            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                                                {section.items?.map((item: any, i: number) => (
                                                    <div key={i} className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow">
                                                        <h3 className="text-xl font-bold mb-3">{item.title}</h3>
                                                        <p className="text-slate-600">{item.description}</p>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    </section>
                                );
                            }

                            return null;
                        })}

                        {!activePage.content?.sections?.length && (
                            <div className="py-20 text-center text-muted">
                                Empty page. Add content in the editor.
                            </div>
                        )}
                    </div>
                ) : (
                    <div>Page not found</div>
                )}
            </main>

            {/* Contact Section */}
            <section id="contact" className="py-20 bg-slate-900 text-white">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
                        <div>
                            <h2 className="text-3xl font-bold mb-6">Get in Touch</h2>
                            <p className="text-slate-400 mb-8 text-lg">
                                Ready to start your next project? Fill out the form below and I'll get back to you as soon as possible with a custom quote.
                            </p>

                            <div className="space-y-6">
                                {profile.email && (
                                    <div className="flex items-center gap-4">
                                        <div className="w-12 h-12 bg-white/10 rounded-full flex items-center justify-center">
                                            <Icons.Mail className="w-6 h-6 text-primary" />
                                        </div>
                                        <div>
                                            <div className="text-sm text-slate-400">Email</div>
                                            <div className="font-medium">{profile.email}</div>
                                        </div>
                                    </div>
                                )}
                                {profile.phone && (
                                    <div className="flex items-center gap-4">
                                        <div className="w-12 h-12 bg-white/10 rounded-full flex items-center justify-center">
                                            <Icons.Phone className="w-6 h-6 text-primary" />
                                        </div>
                                        <div>
                                            <div className="text-sm text-slate-400">Phone</div>
                                            <div className="font-medium">{profile.phone}</div>
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>

                        <div className="bg-white rounded-2xl p-8 text-slate-900">
                            {sent ? (
                                <div className="text-center py-12">
                                    <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                                        <Icons.Check className="w-8 h-8 text-green-600" />
                                    </div>
                                    <h3 className="text-xl font-bold mb-2">Message Sent!</h3>
                                    <p className="text-slate-600">Thanks for reaching out. I'll be in touch shortly.</p>
                                    <button onClick={() => setSent(false)} className="mt-6 text-primary font-medium hover:underline">Send another</button>
                                </div>
                            ) : (
                                <form onSubmit={handleContactSubmit} className="space-y-4">
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 mb-1">Name</label>
                                        <input
                                            type="text"
                                            required
                                            className="w-full px-4 py-3 rounded-lg border border-slate-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                                            placeholder="Your Name"
                                            value={formState.name}
                                            onChange={e => setFormState({ ...formState, name: e.target.value })}
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 mb-1">Email</label>
                                        <input
                                            type="email"
                                            required
                                            className="w-full px-4 py-3 rounded-lg border border-slate-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                                            placeholder="you@company.com"
                                            value={formState.email}
                                            onChange={e => setFormState({ ...formState, email: e.target.value })}
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 mb-1">Phone</label>
                                        <input
                                            type="tel"
                                            className="w-full px-4 py-3 rounded-lg border border-slate-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                                            placeholder="(555) 123-4567"
                                            value={formState.phone}
                                            onChange={e => setFormState({ ...formState, phone: e.target.value })}
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 mb-1">Message</label>
                                        <textarea
                                            rows={4}
                                            className="w-full px-4 py-3 rounded-lg border border-slate-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all resize-none"
                                            placeholder="How can I help you?"
                                            value={formState.message}
                                            onChange={e => setFormState({ ...formState, message: e.target.value })}
                                        />
                                    </div>
                                    <button
                                        type="submit"
                                        disabled={sending}
                                        className="w-full py-4 bg-primary text-slate-900 font-bold rounded-lg hover:bg-primary/90 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                                    >
                                        {sending ? 'Sending...' : 'Send Message'}
                                    </button>
                                </form>
                            )}
                        </div>
                    </div>
                </div>
            </section>

            {/* Footer */}
            <footer className="bg-slate-950 text-slate-400 py-12 border-t border-slate-800">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center gap-6">
                    <div className="text-sm">
                        © {new Date().getFullYear()} {profile.company || profile.name}. All rights reserved.
                    </div>
                    <div className="text-sm flex gap-6">
                        <a href="#" className="hover:text-white transition-colors">Privacy Policy</a>
                        <a href="#" className="hover:text-white transition-colors">Terms of Service</a>
                    </div>
                </div>
            </footer>
        </div>
    );
};
